# envoy-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: envoy
  template:
    metadata:
      labels:
        app: envoy
    spec:
      containers:
        - name: envoy
          image: envoyproxy/envoy:v1.35.3
          args:
            - "--config-path /etc/envoy/envoy.yaml"
          ports:
            - containerPort: 10000
          volumeMounts:
            - name: envoy-config
              mountPath: /etc/envoy
              readOnly: true
      volumes:
        - name: envoy-config
          configMap:
            name: envoy-config
---
apiVersion: v1
kind: Service
metadata:
  name: envoy-service
spec:
  selector:
    app: envoy
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 10000
    - name: admin
      protocol: TCP
      port: 9901
      targetPort: 9901
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-config
data:
  envoy.yaml: |
    admin:
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 9901
    
    static_resources:
      listeners:
        - name: listener_0
          address:
            socket_address:
              address: 0.0.0.0
              port_value: 10000
          filter_chains:
            - filters:
                - name: envoy.filters.network.http_connection_manager
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                    stat_prefix: ingress_http
                    generate_request_id: true
                    preserve_external_request_id: false
                    route_config:
                      name: local_route
                      virtual_hosts:
                        - name: local_service
                          domains: [ "*" ]
                          routes:
                            - match:
                                prefix: "/"
                              route:
                                cluster: echo_service
                                hash_policy:
                                  - header:
                                      header_name: x-request-id
                                    terminal: true
                    http_filters:
                      - name: envoy.filters.http.router
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
    
      clusters:
        - name: echo_service
          connect_timeout: 0.25s
          type: STRICT_DNS
          lb_policy: MAGLEV
          maglev_lb_config:
            table_size: 65537
          load_assignment:
            cluster_name: echo_service
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: echo-service
                          port_value: 80
          health_checks:
            - timeout: 1s
              interval: 5s
              healthy_threshold: 2
              unhealthy_threshold: 3
              http_health_check:
                path: "/"
          circuit_breakers:
            thresholds:
              - priority: DEFAULT
                max_requests: 1000
                max_pending_requests: 100
                max_retries: 3

